; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino

; change microcontroller
board_build.mcu = atmega328p

; change MCU frequency
board_build.f_cpu = 16000000L

; set upload speed
upload_speed = 115200

; serial port to upload code
upload_port = COM4

; serial monitor port
monitor_port = COM4

; serial monitor speed
monitor_speed = 115200

; serial monitor setup
monitor_filters = time, default, log2file

; libraries
lib_deps = 
    ;adafruit/CAN Adafruit Fork@^1.2.1
    CANDriver=https://github.com/MrNoname3/arduino-CAN.git
    fastled/FastLED@^3.5.0
    arsadri/PushButton Event Modelling Library@^1.0.0
    ;DFPlayerMiniFast=https://github.com/MrNoname3/DFPlayerMini_Fast
    DFPlayerMiniFast=https://github.com/MrNoname3/DFPlayerMiniFast
    