; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;****************** ENV BASE ******************
[env]
framework = arduino
monitor_speed = 115200                                  ; serial monitor speed
monitor_filters = time, default, log2file               ; serial monitor setup
check_tool = cppcheck, clangtidy
check_skip_packages = yes
check_src_filters = src/*
check_flags = 
  cppcheck: --suppress=*:*.pio\* --suppress=noExplicitConstructor --suppress=unusedFunction ;--suppress=*:*lib\ab.cpp
  clangtidy: --checks=clang-analyzer-*,readability-*,performance-*,hicpp-*,bugprone-*,modernize-*,-modernize-use-trailing-return-type ;--suppress=readability-magic-numbers
extra_scripts =
  pre:getCommitHash.py
; build options
build_flags =
  '-D BUILD_ENV_NAME="$PIOENV"'
  '-D MONITOR_BAUD=${env.monitor_speed}'
  '-D GIT_COMMIT_HASH=$GIT_COMMIT_HASH'
  '-D GIT_COMMIT_COUNT=$GIT_COMMIT_COUNT'

;****************** ENV:ESP8266_BASE ******************
[env:esp8266_base]
platform = espressif8266
board = d1_mini
platform_packages = platformio/framework-arduinoespressif8266@^3.30102.0
board_build.mcu = esp8266                       ; Microcontroller
board_build.f_cpu = 160000000L                  ; MCU frequency
board_build.f_flash = 80000000L                 ; External SPI FLASH speed
board_build.flash_mode = qio                    ; SPI FLASH uplad method
monitor_port = COM3                             ; serial monitor port
upload_port = COM3                              ; serial port to upload code
upload_speed = 921600                           ; set upload speed
upload_protocol = esptool                       ; set upload protocol -> Serial upload
upload_resetmethod = nodemcu
board_build.filesystem = littlefs               ; Used filesystem on SPI's FS space
board_build.ldscript = eagle.flash.4m2m.ld      ; FLASH partitioning: sketch-1019KB, OTA-1028KB, FS-2024KB
monitor_filters =
  ${env.monitor_filters}
  esp8266_exception_decoder
build_flags =
  ${env.build_flags}
  -D ATOMIC_FS_UPDATE
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
  -D BEARSSL_SSL_BASIC
  -D VTABLES_IN_FLASH
  ;-D DEBUG_ESP_PORT=Serial
  ;-D DEBUG_ESP_SSL
  ;-D DEBUG_ESP_TLS_MEM
  ;-D DEBUG_ESP_HTTP_CLIENT
  ;-D DEBUG_ESP_HTTP_SERVER
  ;-D DEBUG_ESP_CORE
  ;-D DEBUG_ESP_WIFI
  ;-D DEBUG_ESP_HTTP_UPDATE
  ;-D DEBUG_ESP_UPDATER
  ;-D DEBUG_ESP_OTA

build_src_filter =
  -<*>
  +<main.cpp>

;****************** ENV:PROJECT_ESP8266_RAD ******************
[env:project_esp8266_rad]
extends = env:esp8266_base
;build_type = debug
build_flags =
  ${env:esp8266_base.build_flags}
  '-D MQTT_MAX_PACKET_SIZE=1024'

; libraries
lib_deps =
  MQTTClient=https://github.com/MrNoname3/pubsubclient.git
  JSONHandler=bblanchon/ArduinoJson@^7.1.0

build_src_filter =
  -<*>
  +<main_esp8266_rad.cpp>

;****************** ENV:PROJECT_ESP8266_SMOKE ******************
[env:project_esp8266_smoke]
extends = env:esp8266_base
;build_type = debug
build_flags =
  ${env:esp8266_base.build_flags}
  '-D MQTT_MAX_PACKET_SIZE=1024'

; libraries
lib_deps =
  MQTTClient=https://github.com/MrNoname3/pubsubclient.git
  JSONHandler=bblanchon/ArduinoJson@^7.1.0
  ADS1115=robtillaart/ADS1X15@^0.5.0
  MQ135GasSensor=miguel5612/MQUnifiedsensor@^3.0.0

build_src_filter =
  -<*>
  +<main_esp8266_smoke.cpp>

;****************** ENV:PROJECT_ESP8266_CAN ******************
;[env:project_esp8266_can]
;extends = env:esp8266_base
;build_flags =
;  ${env:esp8266_base.build_flags}
;lib_deps =
;  CANDriver=https://github.com/MrNoname3/arduino-CAN.git

;****************** ENV:ESP32_BASE ******************
[env:esp32_base]
platform = espressif32
board = lolin32
platform_packages =
board_build.mcu = esp32                         ; Microcontroller
board_build.f_cpu = 240000000L                  ; Set CPU frequency to 240MHz.
board_build.f_flash = 80000000L                 ; Set flash frequency to 80MHz.
board_build.flash_mode = dio                    ; Flash chip interface mode.
board_upload.flash_size = 4MB                   ; Set flash size.
board_upload.maximum_size = 4194304
monitor_port = COM6                             ; Select serial monitor port.
upload_port = COM6                              ; Select serial port to upload code.
upload_speed = 921600                           ; Set upload speed.
upload_protocol = esptool                       ; Serial->esptool, debugger->esp-prog
board_build.filesystem = littlefs               ; Used filesystem on SPI's FS space
board_build.partitions = default.csv
monitor_filters =
  ${env.monitor_filters}
  esp32_exception_decoder
build_flags =
  ${env.build_flags}
  -DCORE_DEBUG_LEVEL=1                          ; Debug level -> 0:none, 1:error, 2:warn, 3:info, 4:debug, 5:verbose
debug_tool = esp-prog                           ; Debugger options.
debug_init_break = tbreak setup                 ; It stops the program at "void setup()" function.
debug_speed = 20000                             ; Fixed debug speed in kHz.

build_src_filter =
  -<*>
  +<main.cpp>

;****************** ENV:PROJECT_ESP32_CAN ******************
[env:project_esp32_can]
extends = env:esp32_base
build_flags =
  ${env:esp32_base.build_flags}
  '-D MQTT_MAX_PACKET_SIZE=1024'
  '-D MASTER_CAN_ADDRESS=10U'
; libraries
lib_deps =
  MQTTClient=https://github.com/MrNoname3/pubsubclient.git
  JSONHandler=bblanchon/ArduinoJson@^7.1.0
  CANDriver=https://github.com/MrNoname3/arduino-CAN.git

build_src_filter =
  -<*>
  +<main_esp32_can.cpp>