; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nanoatmega328_base

[env]
framework = arduino
monitor_speed = 115200                                  ; serial monitor speed
monitor_filters = time, default, log2file               ; serial monitor setup
check_tool = cppcheck, clangtidy
check_skip_packages = yes
check_src_filters = src/*
check_flags = 
  cppcheck: --suppress=*:*.pio\* --suppress=noExplicitConstructor --suppress=unusedFunction ;--suppress=*:*lib\ab.cpp
  clangtidy: --checks=clang-analyzer-*,readability-*,performance-*,hicpp-*,bugprone-*,modernize-*,-modernize-use-trailing-return-type ;--suppress=readability-magic-numbers
extra_scripts = 
  pre:scripts/git_commit_info.py
; build options
build_flags =
  '-D BUILD_ENV_NAME="$PIOENV"'
  '-D MONITOR_BAUD=${env.monitor_speed}'
  '-D GIT_COMMIT_HASH=$GIT_COMMIT_HASH'
  '-D GIT_COMMIT_COUNT=$GIT_COMMIT_COUNT'
  '-D GIT_DIRTY=$GIT_DIRTY'

[env:nanoatmega328_base]
platform = atmelavr
board = nanoatmega328new
platform_packages = platformio/tool-avrdude@^1.70200.0
board_build.mcu = atmega328p                    ; Microcontroller
board_build.f_cpu = 16000000L                   ; MCU frequency
monitor_port = COM3                             ; serial monitor port
upload_port = COM3                              ; serial port to upload code
upload_speed = 115200                           ; set upload speed
;upload_protocol = arduino                       ; set upload protocol -> Serial upload via Optiboot / Urboot bootloader
upload_protocol = urclock                       ; set upload protocol -> Serial upload via Urboot bootloader
;upload_protocol = usbasp                        ; set upload protocol -> ISP upload via USBAsp programmer
;upload_protocol = avrisp                        ; set upload protocol -> ISP upload via Arduino as ISP programmer
;board_upload.maximum_size = 31744               ; Our bootloader section is only 1024byte. Real available flash size is: 32Kb - 1Kb.
board_upload.maximum_size = 32256               ; Our bootloader section is only 512byte. Real available flash size is: 32Kb - 0.5Kb.
extra_scripts = 
  ${env.extra_scripts}
  post:scripts/elf_to_bin.py
; build options
build_flags =
  ${env.build_flags}
  '-D PROGRAM_MEMORY_SIZE=${env:nanoatmega328_base.board_upload.maximum_size}'
  '-D MASTER_CAN_ADDRESS=10U'
  ;'-D NEW_CAN_ADDRESS = 26U'
  ;-D DEBUG_ON

build_src_filter =
  -<*>
  +<main.cpp>

; libraries
lib_deps = 

[env:nanoatmega328_bootloader_urboot771]
extends = env:nanoatmega328_base
upload_protocol = usbasp
;https://eleccelerator.com/fusecalc/fusecalc.php?chip=atmega328p&LOW=FF&HIGH=D4&EXTENDED=FC&LOCKBIT=CF
board_fuses.lfuse = 0xFF    ;original: FF
board_fuses.hfuse = 0xD4    ;original: DA
board_fuses.efuse = 0xFC    ;original: FD
;board_fuses.lock = 0xCF     ;original: 0F

board_bootloader.file = ./bootloader/urboot_771_m328p_1s_x16m0_115k2_uart0_rxd0_txd1_led+d4_csb0_dual_ee_ce_hw_stk500.hex
board_bootloader.lfuse = 0xFF           ;original: FF
board_bootloader.hfuse = 0xD4           ;original: DA
board_bootloader.efuse = 0xFC           ;original: FD
board_bootloader.lock_bits = 0xCF       ;original: 0F
board_bootloader.unlock_bits = 0xFF     ;original: 3F

[env:nanoatmega328_bootloader_urboot800]
extends = env:nanoatmega328_base
upload_protocol = usbasp
;https://eleccelerator.com/fusecalc/fusecalc.php?chip=atmega328p&LOW=FF&HIGH=D6&EXTENDED=FC&LOCKBIT=CF
board_fuses.lfuse = 0xFF    ;original: FF
board_fuses.hfuse = 0xD6    ;original: DA
board_fuses.efuse = 0xFC    ;original: FD
;board_fuses.lock = 0xCF     ;original: 0F

board_bootloader.file = ./bootloader/urboot_800_m328p_1s_x16m0_115k2_uart0_rxd0_txd1_led+d4_csb0_dual_ee_ce_hw.hex
board_bootloader.lfuse = 0xFF           ;original: FF
board_bootloader.hfuse = 0xD6           ;original: DA
board_bootloader.efuse = 0xFC           ;original: FD
board_bootloader.lock_bits = 0xCF       ;original: 0F
board_bootloader.unlock_bits = 0xFF     ;original: 3F

[env:nanoatmega328_alert]
extends = env:nanoatmega328_base
build_flags =
  ${env:nanoatmega328_base.build_flags}
  -D PROJECT_ALERT
build_src_filter =
  -<*>
  +<main_alert.cpp>
  +<lib/canHandler/*>
  +<lib/crc16/*>
  +<lib/eepromHandler/*>
  +<lib/ota/*>
  +<lib/PushButtonHandler/*>
  +<lib/rgbLedWrapper/*>
  +<lib/CircularBuffer/*>
  +<lib/ambientSensor/*>
  +<lib/dfPlayer/*>
  +<lib/externalSensor/*>
  +<lib/taskRunner/*>
lib_deps = 
  ${env:nanoatmega328_base.lib_deps}
  CANDriver=https://github.com/MrNoname3/arduino-CAN.git
  WS2812Driver=makuna/NeoPixelBus@^2.7.6
  SPIFlash=lowpowerlab/SPIFlash@^101.1.3
  DFPlayerMiniFast=https://github.com/MrNoname3/DFPlayerMiniFast
  SI7021Driver=https://github.com/MrNoname3/SI7021.git#dev

[env:nanoatmega328_irrigation]
extends = env:nanoatmega328_base
build_flags =
  ${env:nanoatmega328_base.build_flags}
  -D PROJECT_IRRIGATION
build_src_filter =
  -<*>
  +<main_irrigation.cpp>
  +<lib/canHandler/*>
  +<lib/crc16/*>
  +<lib/eepromHandler/*>
  +<lib/ota/*>
  +<lib/PushButtonHandler/*>
  +<lib/rgbLedWrapper/*>
  +<lib/taskRunner/*>
  +<lib/pcf8574/*>
  +<lib/pumpControl/*>
  +<lib/multiplexer/*>
  +<lib/moistureReader/*>
lib_deps = 
  ${env:nanoatmega328_base.lib_deps}
  CANDriver=https://github.com/MrNoname3/arduino-CAN.git
  WS2812Driver=makuna/NeoPixelBus@^2.7.6
  SPIFlash=lowpowerlab/SPIFlash@^101.1.3